trigger:
  branches:
    include:
      - main
pool:
  name: Azure Pipelines
steps:
  - task: Docker@2
    displayName: Build and push
    inputs:
      containerRegistry: $(ACR_SERVICE_CONNECTION)
      repository: $(CKAN_IMAGE_NAME)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      buildContext: 'ckanext-weca-tdh'
  - task: Docker@2
    displayName: Save an image
    inputs:
      repository: '$(CKAN_IMAGE_NAME)'
      command: 'save'
      arguments: '-o $(build.artifactstagingdirectory)/$(CKAN_IMAGE_NAME).image.tar $(AZURE_CONTAINER_REGISTRY).azurecr.io/$(CKAN_IMAGE_NAME):$(Build.BuildId)'  
  - task: AzureContainerApps@1
    displayName: Update revision
    inputs:
      connectedServiceNameARM: $(ARM_SERVICE_CONNECTION)
      containerAppName: $(CONTAINER_APP_NAME)
      resourceGroup: $(CONTAINER_APP_RESOURCE_GROUP)
      imageToDeploy: $(AZURE_CONTAINER_REGISTRY).azurecr.io/$(CKAN_IMAGE_NAME):$(Build.BuildId)
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ckan-build'
      publishLocation: 'Container'
