# Dataset column headers
DATASET_NAME = 'Name'
DATASET_TITLE = 'Title'
DATASET_SOURCE = 'Source'
DATASET_PUBLISHER = 'Publisher'
DATASET_DATA_AGREEMENTS = 'Data agreements'
DATASET_LICENSE = 'License'
DATASET_NOTES = 'Description'
DATASET_AVAILABILITY = 'Availability'
DATASET_VISIBILITY = 'Catalogue visibility'
DATASET_FEATURED = 'Featured'
DATASET_TAGS = 'Tags'
DATASET_TOPICS = 'Topics'
RESOURCE_TITLE = 'Resource title'
RESOURCE_DESCRIPTION = 'Resource description'
RESOURCE_URL = 'Resource url'
RESOURCE_FORMAT = 'Resource format'
RESOURCE_DATA_CATEGORY = 'Resource data category'
RESOURCE_DATA_ACCESS_TYPE = 'Resource data access type'
RESOURCE_DATE_CREATED = 'Resource date created'
RESOURCE_DATA_LAYER = 'Resource data layer'
RESOURCE_TDH_CATALOG = 'Resource TDH catalog'
RESOURCE_TDH_TABLE = 'Resource TDH table'
DATASET_DATA_OWNERS = 'Data owners'
DATASET_DATA_STEWARDS = 'Data stewards'
DATASET_DATE_CREATED = 'Date created'
DATASET_LAST_MODFIED = 'Last modified'
DATASET_LAST_REVIEWED = 'Last reviewed'
DATASET_DATA_QUALITY_CATEGORY = 'Data quality category'
DATASET_DATA_QUALITY_SCORE = 'Data quality score'
DATASET_USER_GROUP = 'AD user group'

# Publisher column headers
PUBLISHER_GUID = 'GUID'
PUBLISHER_SLUG = 'Slug'
PUBLISHER_TITLE = 'Title'
PUBLISHER_DESC = 'Description'
PUBLISHER_LOGO = 'Logo'
PUBLISHER_PARENT_ORG = 'Parent Organisation'
PUBLISHER_TDH_SCHEMA = 'TDH Schema'

# Topic column headers
TOPIC_GUID = 'GUID'
TOPIC_SLUG = 'Slug'
TOPIC_TITLE = 'Title'
TOPIC_DESC = 'Description'
TOPIC_LOGO = 'Logo'
