name: Build and test CKAN 2.11 TDH extension images
on: 
    push:
      paths:
        - 'ckanext-weca-tdh/**'
        - '.github/**'
    pull_request:
      paths:
        - 'ckanext-weca-tdh/**'
jobs:
  test:
    name: Test CKAN 2.11.1-1.16
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:2.11.1-py3.10
      options: --user root
    services:
      solr:
        image: ckan/ckan-solr:2.11-solr9
      postgres:
        image: ckan/ckan-postgres-dev:2.11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
    defaults:
        run:
          working-directory: ckanext-weca-tdh
    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install -e .
          # Replace default path to CKAN core config file with the one on the container
          sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
          ckan -c test.ini db init

      - name: Run tests
        run: pytest --ckan-ini=test.ini --cov=ckanext.archiver --disable-warnings ckanext/archiver/tests
